name: mbus_parser
description: A robust Dart parser for Wireless M-Bus (EN 13757-4) and Wired M-Bus (EN 13757-3) telegrams, with built-in AES decryption and record decoding.
version: 0.0.2
repository: https://github.com/seetherisingazeez/mbus_parser

environment:
  sdk: ^3.11.1

dependencies:
  pointycastle: ^4.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
